#!/bin/bash
./scripts/textcleaner -e stretch -f 45 -a 10 $1 $1-tmp.png
magick convert $1-tmp.png -threshold 25% $1-tmp2.png
./scripts/textcleaner -e stretch -f 50 -t 20 -s 10 -a 25 $1-tmp2.png $1-out.png
